version: 0.1

phases:
  pre-build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - echo Building with npm
      - npm run webpack
artifacts:
  files:
    - index.html
    - react.html
    - favicon.ico
    - styles/*
    - images/*
    - dist/*